server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: resume-service
              uri: lb://resume-service
              predicates:
                - Path=/api/resumes/**
            - id: job-service
              uri: lb://job-service
              predicates:
                - Path=/api/jobs/**
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/applications/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
