server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: resume-service
          uri: lb://resume-service
          predicates:
            - Path=/api/resumes/**
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/applications/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
