server:
  port: 8761

spring:
  application:
    name: eureka-server

# Minimal Eureka Server structural config
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
