server.port=8800

spring.application.name=config-server
spring.profiles.active=native

spring.cloud.config.server.native.search-locations[0]=file:./config/{profile}
spring.cloud.config.server.native.search-locations[1]=file:../../config/{profile}
spring.cloud.config.server.native.search-locations[2]=file:/app/config/{profile}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
